version: "3"

services:
  api-gateway:
    container_name: api-gateway-container
    build: ./
    ports:
      - 5050:5050
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - EUREKA_URL=${EUREKA_URL}
      - KAFKA_URL=${KAFKA_URL}
      - POSTGRES_URL=${POSTGRES_URL}
    volumes:
      - .m2:/root/.m2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/health"]
      interval: 10s
      timeout: 5s
      retries: 1000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    extra_hosts:
      - "host.docker.internal:host-gateway"