version: "3"

services:
  api-gateway:
    container_name: api-gateway-container
    build: ./
    ports:
      - 5050:5050
    environment:
      - JWT_SECRET_KEY="my-secret-key"
      - EUREKA_URL="http://host.docker.internal:8761/eureka"
      - KAFKA_URL="http://host.docker.internal:9092"
    volumes:
      - .m2:/root/.m2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/health"]
      interval: 10s
      timeout: 5s
      retries: 1000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    extra_hosts:
      - "host.docker.internal:host-gateway"