version: "3"

services:
  user-api:
    container_name: user-api-container
    build: ./
    ports:
      - 5151:5151
    environment:
      - JWT_SECRET_KEY="my-secret-key"
      - EUREKA_URL="http://host.docker.internal:8761/eureka"
      - KAFKA_URL="http://host.docker.internal:9092"
      - POSTGRES_URL="jdbc:postgresql://host.docker.internal:5432/netflixClone"
    volumes:
      - .m2:/root/.m2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5151/health"]
      interval: 10s
      timeout: 5s
      retries: 1000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    extra_hosts:
      - "host.docker.internal:host-gateway"