server:
    port: 5353
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true

spring:
    application:
        name: messaging-service
    cache:
        type: redis
    redis:
        host: localhost
        port: 6379
        password: netflixredis6379
    kafka:
        bootstrap-servers: localhost:9092

logging:
    level:
        org.apache.kafka: ERROR

email:
    aws:
        credentials: 
            secret-key: blablabla
        region: 
            static: blablabla

mongo:
    username: mongo
    password: password
    server: localhost:27017
    database: netflixClone
